### ISSUE TITLE
Not compatible with typescript jest config file

### ISSUE THREAD

**Issue by abarghoud** [rbardini/jest-it-up#24]
When referencing a jest config file that's in typescript

`jest-it-up --config=packages/models/jest.config.ts`

I get the following error

```
export default {
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at getData (.../node_modules/jest-it-up/lib/getData.js:5:18)
    at module.exports (.../node_modules/jest-it-up/lib/index.js:23:43)

Node.js v20.11.1
```

**Comment by palerique** [comment]
Do you have plans for supporting TS?

**Comment by rbardini** [comment]
No plans, but I'd be happy to accept contributions towards that!

**Comment by kaspar-p** [comment]
Also not compatible with ESM-style javascript, which also has `export default` at the front.
